# -*- coding: utf-8 -*-
<<<<<<< HEAD
# Generated by Django 1.11.8 on 2018-05-02 02:15
from __future__ import unicode_literals

from django.db import migrations, models
=======
# Generated by Django 1.11.8 on 2018-06-27 06:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 3a1dc066952b3a19848d6e4f39f8bca20bc9f41b


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=20)),
                ('upwd', models.CharField(max_length=30)),
                ('uemail', models.EmailField(max_length=254)),
                ('uname', models.CharField(max_length=30)),
                ('isActive', models.BooleanField(default=True)),
            ],
=======
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='价格')),
                ('spec', models.CharField(max_length=50, verbose_name='规格')),
                ('picture', models.ImageField(upload_to='static/upload/goods', verbose_name='图片路径')),
                ('isActive', models.BooleanField(default=True, verbose_name='上架')),
            ],
            options={
                'verbose_name_plural': '商品',
            },
        ),
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='名称')),
                ('picture', models.ImageField(upload_to='static/upload/goodstype', verbose_name='图片路径')),
                ('desc', models.CharField(max_length=100, verbose_name='描述')),
            ],
            options={
                'verbose_name_plural': '商品类型',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uphone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('upwd', models.CharField(max_length=20, verbose_name='密码')),
                ('uemail', models.EmailField(max_length=254, null=True, verbose_name='电子邮箱')),
                ('uname', models.CharField(max_length=20, verbose_name='姓名')),
                ('isActive', models.BooleanField(default=True, verbose_name='活跃账户')),
            ],
            options={
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='goodstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.GoodsType', verbose_name='商品类型'),
>>>>>>> 3a1dc066952b3a19848d6e4f39f8bca20bc9f41b
        ),
    ]
