# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-10 13:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shuxing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naili', models.CharField(max_length=20)),
                ('tili', models.CharField(max_length=20)),
                ('liliang', models.CharField(max_length=20)),
                ('zhili', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Zhuangbei',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shuxing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shuxing.Shuxing')),
            ],
        ),
    ]
