# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-10 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuxing', '0002_auto_20180910_1347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zb_type',
            old_name='shouzhu',
            new_name='zbb_type',
        ),
        migrations.RemoveField(
            model_name='zb_type',
            name='toukui',
        ),
        migrations.RemoveField(
            model_name='zb_type',
            name='xianglian',
        ),
    ]
