# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-10 14:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shuxing', '0004_auto_20180910_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zhuangbei',
            name='shuxing',
        ),
        migrations.DeleteModel(
            name='Shuxing',
        ),
    ]
